  Invoked by the throw construct, receives the class of exception being thrown as the only argument      